name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Triggers on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Pull latest code

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.ananya556 }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.ananya556 }}/fastapi-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.ananya556 }}/fastapi-app:latest
